Feature/picks buffs
Team-Swamp/Brackeys-Gamejam-2023.2 pull request #11
Opened 2023-08-23 17:51 UTC by bas-boop

2023-08-23 18:37 UTC, Tatum13 approved these changes

2023-08-23 18:37 UTC, Tatum13 commented
Ja nee het werkt

2023-08-24 14:42 UTC, rickdohmen commented on Assets/Scripts/Framework/Pick-ups/Buffs/GunBuff.cs
> +public class GunBuff : MonoBehaviour, IPickup
```suggestion
public sealed class GunBuff : MonoBehaviour, IPickup
```

2023-08-24 14:42 UTC, rickdohmen commented on Assets/Scripts/Framework/Pick-ups/Buffs/SpeedBuff.cs
> +public class SpeedBuff : MonoBehaviour, IPickup
```suggestion
public sealed class SpeedBuff : MonoBehaviour, IPickup
```

2023-08-24 14:45 UTC, rickdohmen requested changes

2023-08-24 14:45 UTC, rickdohmen commented on Assets/Scripts/Framework/Pick-ups/Buffs/GunBuff.cs
> +public class GunBuff : MonoBehaviour, IPickup
```suggestion
public sealed class GunBuff : MonoBehaviour, IPickup
```

2023-08-24 14:45 UTC, rickdohmen commented on Assets/Scripts/Framework/Pick-ups/Buffs/HealthBuff.cs
> +public class HealthBuff : MonoBehaviour, IPickup
```suggestion
public sealed class HealthBuff : MonoBehaviour, IPickup
```

2023-08-24 14:45 UTC, rickdohmen commented on Assets/Scripts/Framework/Pick-ups/Buffs/SpeedBuff.cs
> +public class SpeedBuff : MonoBehaviour, IPickup
```suggestion
public sealed class SpeedBuff : MonoBehaviour, IPickup
```

2023-08-24 18:10 UTC, rickdohmen approved these changes

2023-08-24 18:10 UTC, merged