Feature/room system
Team-Swamp/Brackeys-Gamejam-2023.2 pull request #9
Opened 2023-08-23 16:31 UTC by bas-boop

2023-08-23 18:39 UTC, Tatum13 requested changes

2023-08-23 18:39 UTC, Tatum13 commented on Assets/Scripts/Framework/Rooms/RoomManger.cs
> +    [Header("Uninty Event's")]
```suggestion
    [Header("Unity events")]
```

2023-08-23 18:41 UTC, Tatum13 approved these changes

2023-08-23 18:42 UTC, Tatum13 requested changes
![image](https://github.com/Team-Swamp/Brackeys-Gamejam-2023.2/assets/70800120/4f23c35d-0281-4340-b80b-cbfdb9efe31d)
RoomManager*

2023-08-23 18:44 UTC, Tatum13 approved these changes

2023-08-24 14:51 UTC, rickdohmen approved these changes

2023-08-24 18:02 UTC, merged